# Generated by Django 6.0.5 on 2026-05-15 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.CharField(help_text='예: PORK_LOIN_G', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='재료명')),
                ('category', models.CharField(blank=True, choices=[('돈까스', '돈까스'), ('우동', '우동'), ('만두', '만두'), ('공통', '공통'), ('안주', '안주'), ('포장', '포장'), ('기타', '기타')], max_length=20, verbose_name='카테고리')),
                ('purchase_quantity', models.FloatField(help_text='예: 1kg을 그램으로 환산한 1000', verbose_name='구매 수량')),
                ('purchase_price', models.PositiveIntegerField(verbose_name='구매 가격(원)')),
                ('unit', models.CharField(default='g', max_length=20, verbose_name='단위')),
                ('memo', models.TextField(blank=True, verbose_name='메모')),
            ],
            options={
                'verbose_name': '식자재',
                'verbose_name_plural': '식자재',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.CharField(help_text='예: M001', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='메뉴명')),
                ('category', models.CharField(choices=[('돈까스', '돈까스'), ('우동', '우동'), ('만두', '만두'), ('세트', '세트'), ('안주', '안주'), ('기타', '기타')], max_length=20, verbose_name='카테고리')),
                ('price', models.PositiveIntegerField(verbose_name='판매가(원)')),
                ('monthly_orders', models.PositiveIntegerField(default=0, verbose_name='월 판매량')),
                ('packaging_cost', models.PositiveIntegerField(default=0, verbose_name='포장 비용(원)')),
                ('is_active', models.BooleanField(default=True, verbose_name='판매중')),
            ],
            options={
                'verbose_name': '메뉴',
                'verbose_name_plural': '메뉴',
                'ordering': ['menu_id'],
            },
        ),
        migrations.CreateModel(
            name='ProfitAssumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='기본 가정', max_length=50, verbose_name='가정 이름')),
                ('dine_in_share', models.FloatField(default=0.5, verbose_name='홀 비중')),
                ('delivery_share', models.FloatField(default=0.3, verbose_name='배달 비중')),
                ('takeout_share', models.FloatField(default=0.2, verbose_name='포장 비중')),
                ('delivery_commission_rate', models.FloatField(default=0.12, verbose_name='배달앱 수수료율')),
                ('rider_fee', models.PositiveIntegerField(default=4600, verbose_name='배달 기사 수수료(원)')),
                ('rider_fee_store_share', models.FloatField(default=1.0, verbose_name='기사료 가게 부담률')),
                ('target_food_cost_rate', models.FloatField(default=0.35, verbose_name='목표 원가율')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '손익 가정',
                'verbose_name_plural': '손익 가정',
            },
        ),
        migrations.CreateModel(
            name='MenuProfitSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_cost', models.FloatField(verbose_name='재료 원가')),
                ('food_cost_rate', models.FloatField(verbose_name='원가율')),
                ('dine_in_margin', models.FloatField(verbose_name='홀 마진')),
                ('takeout_margin', models.FloatField(verbose_name='포장 마진')),
                ('delivery_margin', models.FloatField(verbose_name='배달 마진')),
                ('weighted_margin', models.FloatField(verbose_name='가중 마진')),
                ('monthly_profit', models.FloatField(verbose_name='월 예상 이익')),
                ('monthly_revenue', models.FloatField(verbose_name='월 매출')),
                ('signal', models.CharField(max_length=50, verbose_name='신호등')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='profit.menu')),
            ],
            options={
                'verbose_name': '수익성 스냅샷',
                'verbose_name_plural': '수익성 스냅샷',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='사용량')),
                ('memo', models.CharField(blank=True, max_length=255)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='used_in', to='profit.ingredient')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_items', to='profit.menu')),
            ],
            options={
                'verbose_name': '레시피 항목',
                'verbose_name_plural': '레시피 항목',
                'ordering': ['menu', 'ingredient'],
                'unique_together': {('menu', 'ingredient')},
            },
        ),
    ]
