# Generated by Django 5.2.13 on 2026-06-24 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0002_profitassumption_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.PositiveIntegerField(verbose_name='이전 구매가(원)')),
                ('new_price', models.PositiveIntegerField(verbose_name='변경 구매가(원)')),
                ('source', models.CharField(choices=[('mock', '모의 시세'), ('kamis', 'KAMIS 시세'), ('manual', '수동 입력')], default='manual', max_length=20, verbose_name='출처')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='비고')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='profit.ingredient')),
            ],
            options={
                'verbose_name': '단가 변경 이력',
                'verbose_name_plural': '단가 변경 이력',
                'ordering': ['-created_at'],
            },
        ),
    ]
