# Generated by Django 5.2.15 on 2026-06-24 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profit', '0003_menuprofitsnapshot_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='accounts.store', verbose_name='매장'),
        ),
        migrations.AddField(
            model_name='menu',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='accounts.store', verbose_name='매장'),
        ),
        migrations.AddField(
            model_name='menuprofitsnapshot',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_snapshots', to='accounts.store', verbose_name='매장'),
        ),
        migrations.AddField(
            model_name='profitassumption',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_assumptions', to='accounts.store', verbose_name='매장'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='ingredient_id',
            field=models.CharField(help_text='예: PORK_LOIN_G', max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='menu_id',
            field=models.CharField(help_text='예: M001', max_length=50),
        ),
        migrations.AddConstraint(
            model_name='ingredient',
            constraint=models.UniqueConstraint(fields=('store', 'ingredient_id'), name='unique_store_ingredient_id'),
        ),
        migrations.AddConstraint(
            model_name='menu',
            constraint=models.UniqueConstraint(fields=('store', 'menu_id'), name='unique_store_menu_id'),
        ),
    ]
