# Generated by Django 5.2.15 on 2026-06-24 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profit', '0004_ingredient_store_menu_store_menuprofitsnapshot_store_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMenuSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_date', models.DateField(verbose_name='판매일')),
                ('channel', models.CharField(choices=[('ALL', '전체'), ('DINE_IN', '홀'), ('DELIVERY', '배달'), ('TAKEOUT', '포장')], default='ALL', max_length=20, verbose_name='판매 채널')),
                ('quantity', models.PositiveIntegerField(verbose_name='판매량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='profit.menu', verbose_name='메뉴')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='accounts.store', verbose_name='매장')),
            ],
            options={
                'ordering': ['-sale_date', 'menu_id'],
                'constraints': [models.UniqueConstraint(fields=('store', 'menu', 'sale_date', 'channel'), name='unique_daily_menu_sale')],
            },
        ),
    ]
