# Generated by Django 5.2.13 on 2026-06-25 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_productionregion_cropgrowthstage_and_more'),
        ('profit', '0004_multitenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='market_item',
            field=models.ForeignKey(blank=True, help_text='가격 예측 대상으로 연동된 시장품목(재료별 1:1)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='market.marketitem', verbose_name='연동 시장품목'),
        ),
    ]
