# Generated by Django 5.2.13 on 2026-06-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0005_ingredient_market_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_supplied',
            field=models.BooleanField(default=False, help_text='본사/업체에서 고정가로 납품받는 재료. 시세 변동이 없으므로 가격 예측에서 제외한다.', verbose_name='납품 재료(고정가)'),
        ),
    ]
