# Generated by Django 5.2.15 on 2026-06-25 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profit', '0006_market_ranking_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropProductionRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=30)),
                ('region_name', models.CharField(max_length=100)),
                ('weight', models.DecimalField(decimal_places=6, max_digits=7)),
                ('mapping_confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('review_status', models.CharField(default='PENDING', max_length=20)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastCalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=100)),
                ('horizon_days', models.PositiveSmallIntegerField()),
                ('target_coverage', models.DecimalField(decimal_places=4, max_digits=5)),
                ('measured_coverage', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('absolute_error_quantile', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fitted_from', models.DateField()),
                ('fitted_to', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ForecastComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_prediction', models.DecimalField(decimal_places=2, max_digits=14)),
                ('weather_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('residual_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('weather_forecast_issued_at', models.DateTimeField(blank=True, null=True)),
                ('details', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField()),
                ('horizon_days', models.PositiveSmallIntegerField()),
                ('median', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lower', models.DecimalField(decimal_places=2, max_digits=14)),
                ('upper', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('model_version', models.CharField(max_length=100)),
                ('feature_version', models.CharField(max_length=100)),
                ('observation_cutoff', models.DateTimeField()),
                ('code_revision', models.CharField(blank=True, max_length=64)),
                ('random_seed', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('RUNNING', '진행 중'), ('SUCCEEDED', '성공'), ('FAILED', '실패')], default='RUNNING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-as_of_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('dataset', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('RUNNING', '진행 중'), ('SUCCEEDED', '성공'), ('PARTIAL', '일부 성공'), ('FAILED', '실패')], default='RUNNING', max_length=20)),
                ('observation_cutoff', models.DateTimeField(blank=True, null=True)),
                ('requested_params', models.JSONField(default=dict)),
                ('source_version', models.CharField(blank=True, max_length=100)),
                ('code_revision', models.CharField(blank=True, max_length=64)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('rejected_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='OutOfFoldForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fold_id', models.CharField(max_length=100)),
                ('train_cutoff', models.DateField()),
                ('target_date', models.DateField()),
                ('horizon_days', models.PositiveSmallIntegerField()),
                ('prediction', models.DecimalField(decimal_places=2, max_digits=14)),
                ('actual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('model_version', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RawSourcePayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.URLField(max_length=1000)),
                ('request_params', models.JSONField(default=dict)),
                ('payload', models.JSONField()),
                ('payload_sha256', models.CharField(max_length=64)),
                ('collected_at', models.DateTimeField()),
            ],
            options={
                'ordering': ['-collected_at'],
            },
        ),
        migrations.CreateModel(
            name='ResidualObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residual', models.DecimalField(decimal_places=2, max_digits=14)),
                ('residual_type', models.CharField(default='ACTUAL_MINUS_PREDICTION', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='StoreSalesImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=255)),
                ('source_sha256', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('STARTED', '진행 중'), ('SUCCEEDED', '성공'), ('FAILED', '실패')], default='STARTED', max_length=20)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('imported_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('forecast_type', models.CharField(max_length=30)),
                ('location_key', models.CharField(max_length=100)),
                ('issued_at', models.DateTimeField()),
                ('valid_at', models.DateTimeField()),
                ('variables', models.JSONField(default=dict)),
                ('collected_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('station_id', models.CharField(max_length=50)),
                ('observed_at', models.DateTimeField()),
                ('variables', models.JSONField(default=dict)),
                ('quality', models.JSONField(default=dict)),
                ('collected_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WeatherStationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('station_id', models.CharField(max_length=50)),
                ('station_name', models.CharField(blank=True, max_length=100)),
                ('grid_x', models.IntegerField(blank=True, null=True)),
                ('grid_y', models.IntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('weight', models.DecimalField(decimal_places=6, default=1, max_digits=7)),
                ('mapping_confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('review_status', models.CharField(default='PENDING', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='WholesaleAuctionObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=100)),
                ('auctioned_at', models.DateTimeField()),
                ('market_code', models.CharField(max_length=50)),
                ('market_name', models.CharField(blank=True, max_length=100)),
                ('source_item_code', models.CharField(max_length=100)),
                ('source_item_name', models.CharField(max_length=100)),
                ('origin_name', models.CharField(blank=True, max_length=100)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('volume', models.DecimalField(decimal_places=3, max_digits=16)),
                ('price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('collected_at', models.DateTimeField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='marketpriceobservation',
            name='unique_market_observation',
        ),
        migrations.AddField(
            model_name='dailymenusale',
            name='discount_amount',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymenusale',
            name='gross_revenue',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailymenusale',
            name='net_revenue',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='standard_unit',
            field=models.CharField(default='kg', max_length=30),
        ),
        migrations.AddField(
            model_name='marketitem',
            name='variety',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketpriceobservation',
            name='market_type',
            field=models.CharField(default='RETAIL', max_length=30),
        ),
        migrations.AddField(
            model_name='marketpriceobservation',
            name='region_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='marketpriceobservation',
            name='region_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketpriceobservation',
            name='source_item_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='marketpriceobservation',
            name='source_unique_key',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='marketpriceobservation',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='cropproductionregion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_regions', to='profit.marketitem'),
        ),
        migrations.AddField(
            model_name='forecastcalibration',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calibrations', to='profit.marketitem'),
        ),
        migrations.AddField(
            model_name='forecastcomponent',
            name='point',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='profit.forecastpoint'),
        ),
        migrations.AddField(
            model_name='forecastrun',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='profit.marketitem'),
        ),
        migrations.AddField(
            model_name='forecastpoint',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='profit.forecastrun'),
        ),
        migrations.AddField(
            model_name='marketforecast',
            name='run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_forecasts', to='profit.forecastrun'),
        ),
        migrations.AddField(
            model_name='outoffoldforecast',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oof_forecasts', to='profit.marketitem'),
        ),
        migrations.AddField(
            model_name='rawsourcepayload',
            name='ingestion_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_payloads', to='profit.ingestionrun'),
        ),
        migrations.AddField(
            model_name='marketpriceobservation',
            name='raw_payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_prices', to='profit.rawsourcepayload'),
        ),
        migrations.AddConstraint(
            model_name='marketpriceobservation',
            constraint=models.UniqueConstraint(fields=('item', 'observed_date', 'source', 'region_code', 'market_type', 'unit'), name='unique_market_observation'),
        ),
        migrations.AddField(
            model_name='residualobservation',
            name='oof_forecast',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residual_observation', to='profit.outoffoldforecast'),
        ),
        migrations.AddField(
            model_name='storesalesimport',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_imports', to='accounts.store'),
        ),
        migrations.AddField(
            model_name='dailymenusale',
            name='source_import',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='profit.storesalesimport'),
        ),
        migrations.AddField(
            model_name='weatherforecastsnapshot',
            name='raw_payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_forecasts', to='profit.rawsourcepayload'),
        ),
        migrations.AddField(
            model_name='weatherobservation',
            name='raw_payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_observations', to='profit.rawsourcepayload'),
        ),
        migrations.AddField(
            model_name='weatherstationmapping',
            name='production_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_mappings', to='profit.cropproductionregion'),
        ),
        migrations.AddField(
            model_name='wholesaleauctionobservation',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_observations', to='profit.marketitem'),
        ),
        migrations.AddField(
            model_name='wholesaleauctionobservation',
            name='raw_payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_observations', to='profit.rawsourcepayload'),
        ),
        migrations.AddConstraint(
            model_name='cropproductionregion',
            constraint=models.UniqueConstraint(fields=('item', 'region_code', 'valid_from'), name='unique_item_production_region_version'),
        ),
        migrations.AddConstraint(
            model_name='forecastcalibration',
            constraint=models.UniqueConstraint(fields=('item', 'model_version', 'horizon_days'), name='unique_forecast_calibration'),
        ),
        migrations.AddConstraint(
            model_name='forecastrun',
            constraint=models.UniqueConstraint(fields=('item', 'as_of_date', 'model_version'), name='unique_forecast_run'),
        ),
        migrations.AddConstraint(
            model_name='forecastpoint',
            constraint=models.UniqueConstraint(fields=('run', 'horizon_days'), name='unique_forecast_point'),
        ),
        migrations.AddConstraint(
            model_name='forecastpoint',
            constraint=models.CheckConstraint(condition=models.Q(('lower__lte', models.F('median'))), name='forecast_lower_lte_median'),
        ),
        migrations.AddConstraint(
            model_name='forecastpoint',
            constraint=models.CheckConstraint(condition=models.Q(('median__lte', models.F('upper'))), name='forecast_median_lte_upper'),
        ),
        migrations.AddConstraint(
            model_name='outoffoldforecast',
            constraint=models.UniqueConstraint(fields=('item', 'fold_id', 'target_date', 'horizon_days', 'model_version'), name='unique_oof_forecast'),
        ),
        migrations.AddConstraint(
            model_name='rawsourcepayload',
            constraint=models.UniqueConstraint(fields=('ingestion_run', 'payload_sha256'), name='unique_raw_payload_per_run'),
        ),
        migrations.AddConstraint(
            model_name='storesalesimport',
            constraint=models.UniqueConstraint(fields=('store', 'source_sha256'), name='unique_store_sales_import_file'),
        ),
        migrations.AddConstraint(
            model_name='weatherforecastsnapshot',
            constraint=models.UniqueConstraint(fields=('provider', 'forecast_type', 'location_key', 'issued_at', 'valid_at'), name='unique_weather_forecast_snapshot'),
        ),
        migrations.AddConstraint(
            model_name='weatherobservation',
            constraint=models.UniqueConstraint(fields=('provider', 'station_id', 'observed_at'), name='unique_weather_observation'),
        ),
        migrations.AddConstraint(
            model_name='weatherstationmapping',
            constraint=models.UniqueConstraint(fields=('production_region', 'provider', 'station_id'), name='unique_region_weather_station'),
        ),
        migrations.AddConstraint(
            model_name='wholesaleauctionobservation',
            constraint=models.UniqueConstraint(fields=('source', 'auctioned_at', 'market_code', 'source_item_code', 'origin_name', 'grade', 'unit'), name='unique_wholesale_auction_observation'),
        ),
    ]
