# Generated by Django 5.2.13 on 2026-06-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0006_ingredient_is_supplied'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='is_supplied',
            field=models.BooleanField(default=False, help_text='본사에서 고정가로 발주받는 재료. 시세 변동이 없으므로 가격 예측에서 제외한다.', verbose_name='본사 발주 재료(고정가)'),
        ),
    ]
