# Generated by Django 5.2.13 on 2026-06-25 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_productionregion_cropgrowthstage_and_more'),
        ('profit', '0007_alter_ingredient_is_supplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='commodity_unit_factor',
            field=models.FloatField(default=1.0, help_text='시장품목 가격(예: 원/kg)을 재료 단위(예: 원/g)로 환산하는 계수. 실 commodity 연결 시 사용(예: 원/kg→원/g = 0.001).', verbose_name='시장품목 단가 환산계수'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='market_item',
            field=models.ForeignKey(blank=True, help_text='가격 예측 대상으로 연동된 시장품목(재료별 1:1). 실 commodity(양파 등) 연결 시 KAMIS·기상 실데이터 예측을 사용한다.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='market.marketitem', verbose_name='연동 시장품목'),
        ),
    ]
