# Generated by Django 5.2.15 on 2026-06-25 01:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profit', '0007_cropproductionregion_forecastcalibration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchasePriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit', models.CharField(max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('supplier', models.CharField(blank=True, max_length=100)),
                ('memo', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_prices', to='profit.ingredient')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_prices', to='accounts.store')),
            ],
            options={
                'ordering': ['-purchased_at'],
            },
        ),
        migrations.CreateModel(
            name='IngredientMarketMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('PENDING', '검토 필요'), ('CONFIRMED', '확정'), ('REJECTED', '제외')], default='PENDING', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_mappings', to='profit.ingredient')),
                ('market_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_mappings', to='profit.marketitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'market_item'), name='unique_ingredient_market_mapping')],
            },
        ),
        migrations.CreateModel(
            name='ProductionStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_code', models.CharField(max_length=30)),
                ('region_name', models.CharField(max_length=100)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('acreage', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('yield_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('production_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=16, null=True)),
                ('unit', models.CharField(max_length=30)),
                ('source', models.CharField(max_length=100)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_statistics', to='profit.marketitem')),
                ('raw_payload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_statistics', to='profit.rawsourcepayload')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'region_code', 'period_start', 'period_end', 'source'), name='unique_production_statistic')],
            },
        ),
        migrations.CreateModel(
            name='WeatherExposureFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of_date', models.DateField()),
                ('windows', models.JSONField(default=dict)),
                ('anomalies', models.JSONField(default=dict)),
                ('feature_version', models.CharField(max_length=100)),
                ('observation_cutoff', models.DateTimeField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_exposures', to='profit.marketitem')),
                ('production_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_exposures', to='profit.cropproductionregion')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'production_region', 'as_of_date', 'feature_version'), name='unique_weather_exposure_feature')],
            },
        ),
    ]
