# Generated by Django 5.2.15 on 2026-06-25 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0008_purchasepriceobservation_ingredientmarketmapping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketmodelmetric',
            name='bias',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='marketmodelmetric',
            name='evaluation_method',
            field=models.CharField(default='ROLLING_ORIGIN_HOLDOUT', max_length=100),
        ),
        migrations.AddField(
            model_name='marketmodelmetric',
            name='interval_width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='marketmodelmetric',
            name='mae',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='marketmodelmetric',
            name='mase',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='marketmodelmetric',
            name='pinball_loss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='marketmodelmetric',
            name='rmse',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='marketmodelmetric',
            name='sample_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ForecastModelComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon_days', models.PositiveSmallIntegerField()),
                ('candidate_version', models.CharField(max_length=100)),
                ('baseline_version', models.CharField(max_length=100)),
                ('metric', models.CharField(default='MAE', max_length=30)),
                ('candidate_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('baseline_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('difference', models.DecimalField(decimal_places=4, max_digits=14)),
                ('ci_lower', models.DecimalField(decimal_places=4, max_digits=14)),
                ('ci_upper', models.DecimalField(decimal_places=4, max_digits=14)),
                ('sample_count', models.PositiveIntegerField()),
                ('method', models.CharField(default='PAIRED_BOOTSTRAP', max_length=50)),
                ('is_significant', models.BooleanField(default=False)),
                ('random_seed', models.PositiveIntegerField(default=42)),
                ('evaluation_start', models.DateField()),
                ('evaluation_end', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_comparisons', to='profit.marketitem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('item', 'horizon_days', 'candidate_version', 'baseline_version', 'metric'), name='unique_forecast_model_comparison')],
            },
        ),
    ]
