# Generated by Django 5.2.15 on 2026-06-25 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0009_marketmodelmetric_bias_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='wholesaleauctionobservation',
            name='unique_wholesale_auction_observation',
        ),
        migrations.AddField(
            model_name='wholesaleauctionobservation',
            name='source_record_id',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddConstraint(
            model_name='wholesaleauctionobservation',
            constraint=models.UniqueConstraint(fields=('source', 'source_record_id'), name='unique_wholesale_auction_observation'),
        ),
    ]
