# Generated by Django 5.2.15 on 2026-06-25 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profit', '0010_remove_wholesaleauctionobservation_unique_wholesale_auction_observation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period_label', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('data_used', models.JSONField(default=list)),
                ('source_documents', models.JSONField(default=list)),
                ('expected_effect', models.TextField(blank=True)),
                ('success_criteria', models.TextField(blank=True)),
                ('stop_criteria', models.TextField(blank=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SAVED', '저장'), ('IN_PROGRESS', '진행 중'), ('COMPLETED', '완료'), ('CANCELLED', '중단')], default='SAVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bossprofit_action_plans', to=settings.AUTH_USER_MODEL)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_plans', to='accounts.store')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
