# Generated by Django 5.2.15 on 2026-06-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profit', '0011_actionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='is_hq_supplied',
            field=models.BooleanField(default=False, help_text='본사에서 납품가가 정해져 공급되는 재료(시장가격 변동 영향이 거의 없음)', verbose_name='본사 납품'),
        ),
    ]
