# Generated by Django 5.2.13 on 2026-06-24 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0002_productionregion_cropgrowthstage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.CharField(max_length=20, unique=True, verbose_name='지점번호')),
                ('name', models.CharField(max_length=50, verbose_name='지점명')),
                ('source', models.CharField(choices=[('asos', '기상청 ASOS'), ('aws_agri', '농촌진흥청 농업기상')], default='asos', max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': '기상 관측소',
                'verbose_name_plural': '기상 관측소',
                'ordering': ['station_id'],
            },
        ),
        migrations.CreateModel(
            name='WeatherObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observed_date', models.DateField(verbose_name='관측일(valid_at)')),
                ('variables', models.JSONField(default=dict, verbose_name='기상 변수')),
                ('quality_flag', models.CharField(default='ok', max_length=20)),
                ('source', models.CharField(default='asos', max_length=20)),
                ('raw_ref', models.CharField(blank=True, max_length=255)),
                ('collected_at', models.DateTimeField(verbose_name='수집 시각')),
                ('first_collected_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weather_observations', to='market.ingestionrun')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='weather.weatherstation')),
            ],
            options={
                'verbose_name': '기상 관측',
                'verbose_name_plural': '기상 관측',
                'ordering': ['station', '-observed_date'],
                'indexes': [models.Index(fields=['station', 'observed_date'], name='weather_wea_station_fc646b_idx'), models.Index(fields=['observed_date'], name='weather_wea_observe_f7ccc6_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'station', 'observed_date'), name='uq_weather_obs_natural_key')],
            },
        ),
        migrations.CreateModel(
            name='WeatherForecastSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('kma_short', '기상청 단기예보(1~3일)'), ('kma_mid', '기상청 중기예보(4~11일)'), ('kma_month', '기상청 1개월 전망(12~30일)')], max_length=20)),
                ('issued_at', models.DateTimeField(verbose_name='발행시각(issued_at)')),
                ('valid_at', models.DateField(verbose_name='예측 대상일(valid_at)')),
                ('variables', models.JSONField(default=dict, verbose_name='예보 변수')),
                ('source', models.CharField(default='kma', max_length=20)),
                ('raw_ref', models.CharField(blank=True, max_length=255)),
                ('collected_at', models.DateTimeField(verbose_name='수집 시각')),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forecast_snapshots', to='market.ingestionrun')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_snapshots', to='market.productionregion')),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forecast_snapshots', to='weather.weatherstation')),
            ],
            options={
                'verbose_name': '기상 예보 스냅샷',
                'verbose_name_plural': '기상 예보 스냅샷',
                'ordering': ['-issued_at', 'valid_at'],
                'indexes': [models.Index(fields=['provider', 'valid_at'], name='weather_wea_provide_7a2459_idx'), models.Index(fields=['issued_at'], name='weather_wea_issued__84e158_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'issued_at', 'valid_at', 'region', 'station'), name='uq_forecast_snapshot_natural_key')],
            },
        ),
        migrations.CreateModel(
            name='WeatherStationMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=1.0, verbose_name='가중치')),
                ('distance_km', models.FloatField(blank=True, null=True, verbose_name='거리(km)')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='station_mappings', to='market.productionregion')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_mappings', to='weather.weatherstation')),
            ],
            options={
                'verbose_name': '지역-관측소 매핑',
                'verbose_name_plural': '지역-관측소 매핑',
                'ordering': ['region', '-weight'],
                'unique_together': {('region', 'station')},
            },
        ),
    ]
