# Generated by Django 5.2.15 on 2026-06-24 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='매장명')),
                ('business_type', models.CharField(choices=[('KOREAN', '한식'), ('WESTERN', '양식'), ('JAPANESE', '일식'), ('CHINESE', '중식'), ('CAFE', '카페·디저트'), ('SNACK', '분식'), ('OTHER', '기타')], default='OTHER', max_length=20, verbose_name='업종')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='지역')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('STORE', '매장 등록'), ('INGREDIENT', '첫 재료 등록'), ('MENU', '첫 메뉴 등록'), ('RECIPE', '레시피 구성'), ('SALES', '판매 데이터 입력'), ('COMPLETE', '첫 분석 완료')], default='INGREDIENT', max_length=20)),
                ('store_completed', models.BooleanField(default=True)),
                ('ingredient_completed', models.BooleanField(default=False)),
                ('menu_completed', models.BooleanField(default=False)),
                ('recipe_completed', models.BooleanField(default=False)),
                ('sales_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='accounts.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', '소유자'), ('MANAGER', '관리자'), ('STAFF', '직원')], default='OWNER', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='accounts.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('store', 'user'), name='unique_store_member')],
            },
        ),
    ]
