# Generated by Django 5.2.13 on 2026-06-24 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0002_productionregion_cropgrowthstage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutOfFoldForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(help_text='이 OOF 예측을 만든 Stage1/2 모델 식별자', max_length=64, verbose_name='기반 모델 버전')),
                ('horizon', models.PositiveSmallIntegerField()),
                ('origin_date', models.DateField(help_text='이 시점까지의 과거만으로 예측했다', verbose_name='예측 기준시점(as_of)')),
                ('target_date', models.DateField(verbose_name='예측 대상일')),
                ('prediction', models.FloatField(verbose_name='OOF 예측값')),
                ('actual', models.FloatField(blank=True, null=True, verbose_name='실제값')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oof_forecasts', to='market.marketitem')),
            ],
            options={
                'verbose_name': 'OOF 예측',
                'verbose_name_plural': 'OOF 예측',
                'ordering': ['item', 'model_version', 'horizon', 'origin_date'],
            },
        ),
        migrations.CreateModel(
            name='ResidualObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('residual', models.FloatField(verbose_name='잔차값')),
                ('residual_type', models.CharField(choices=[('log', '로그 잔차'), ('raw', '원시 잔차')], default='log', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('oof', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='residual', to='forecast.outoffoldforecast')),
            ],
            options={
                'verbose_name': '잔차 관측',
                'verbose_name_plural': '잔차 관측',
                'ordering': ['oof'],
            },
        ),
        migrations.AddIndex(
            model_name='outoffoldforecast',
            index=models.Index(fields=['item', 'model_version', 'horizon', 'target_date'], name='forecast_ou_item_id_4ce3d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='outoffoldforecast',
            constraint=models.UniqueConstraint(fields=('item', 'model_version', 'horizon', 'origin_date', 'target_date'), name='uq_oof_natural_key'),
        ),
    ]
