# Generated by Django 5.2.13 on 2026-06-24 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecast', '0001_initial'),
        ('market', '0002_productionregion_cropgrowthstage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horizon', models.PositiveSmallIntegerField()),
                ('target_date', models.DateField()),
                ('median', models.DecimalField(decimal_places=4, max_digits=14)),
                ('lower_80', models.DecimalField(decimal_places=4, max_digits=14)),
                ('upper_80', models.DecimalField(decimal_places=4, max_digits=14)),
                ('lower_95', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('upper_95', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('confidence', models.CharField(choices=[('HIGH', '높음'), ('MEDIUM', '보통'), ('LOW', '낮음')], default='MEDIUM', max_length=8)),
            ],
            options={
                'verbose_name': '예측 점',
                'verbose_name_plural': '예측 점',
                'ordering': ['run', 'horizon'],
            },
        ),
        migrations.CreateModel(
            name='ModelRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_version', models.CharField(max_length=64, unique=True)),
                ('stage', models.CharField(choices=[('base', 'Base Price'), ('weather', 'Weather & Supply'), ('residual', 'Residual Correction'), ('calibration', 'Interval Calibration'), ('ensemble', 'Ensemble')], max_length=20)),
                ('algorithm', models.CharField(blank=True, max_length=50)),
                ('trained_from', models.DateField(blank=True, null=True)),
                ('trained_to', models.DateField(blank=True, null=True)),
                ('train_snapshot_ref', models.CharField(blank=True, help_text='학습 데이터 snapshot 식별자(재현성)', max_length=128)),
                ('code_version', models.CharField(blank=True, max_length=64)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '모델 레지스트리',
                'verbose_name_plural': '모델 레지스트리',
                'ordering': ['stage', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.DecimalField(decimal_places=4, max_digits=14)),
                ('weather_delta', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('residual_delta', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('weather_disabled', models.BooleanField(default=False)),
                ('residual_disabled', models.BooleanField(default=False)),
                ('point', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='component', to='forecast.forecastpoint')),
            ],
            options={
                'verbose_name': '예측 보정량 분해',
                'verbose_name_plural': '예측 보정량 분해',
            },
        ),
        migrations.CreateModel(
            name='ForecastRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(default='market_price', max_length=20)),
                ('as_of', models.DateField(verbose_name='예측 기준일')),
                ('status', models.CharField(choices=[('success', '성공'), ('failed', '실패'), ('stale', 'stale')], default='success', max_length=12)),
                ('model_versions', models.JSONField(blank=True, default=dict, help_text='{base, weather, residual, calibration}')),
                ('data_quality', models.JSONField(blank=True, default=list)),
                ('weather_forecast_issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_runs', to='market.marketitem')),
            ],
            options={
                'verbose_name': '예측 실행',
                'verbose_name_plural': '예측 실행',
                'ordering': ['-as_of', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='forecastpoint',
            name='run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='forecast.forecastrun'),
        ),
        migrations.AddIndex(
            model_name='forecastrun',
            index=models.Index(fields=['item', 'as_of'], name='forecast_fo_item_id_8d06c6_idx'),
        ),
        migrations.AddConstraint(
            model_name='forecastpoint',
            constraint=models.UniqueConstraint(fields=('run', 'horizon'), name='uq_forecast_point'),
        ),
    ]
