# Generated by Django 5.2.13 on 2026-06-24 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(help_text='예: kamis_daily, wholesale_auction, asos', max_length=40, verbose_name='수집 소스')),
                ('status', models.CharField(choices=[('running', '실행 중'), ('success', '성공'), ('partial', '부분 성공'), ('failed', '실패')], default='running', max_length=20)),
                ('params', models.JSONField(blank=True, default=dict, verbose_name='수집 파라미터')),
                ('code_version', models.CharField(blank=True, help_text='git sha 또는 릴리스 라벨', max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('updated_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('quality_issue_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': '수집 실행',
                'verbose_name_plural': '수집 실행',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='표준 품목 코드 (예: ONION, NAPA_CABBAGE)', max_length=64, unique=True)),
                ('name', models.CharField(max_length=100, verbose_name='품목명')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='부류')),
                ('variety', models.CharField(blank=True, max_length=50, verbose_name='품종')),
                ('standard_unit', models.CharField(default='g', help_text='표준단위: g / ml / ea', max_length=10)),
                ('source', models.CharField(choices=[('kamis', 'KAMIS'), ('wholesale', '도매시장 경락'), ('manual', '수동 등록')], default='kamis', max_length=20, verbose_name='출처')),
                ('source_category_code', models.CharField(blank=True, max_length=20)),
                ('source_item_code', models.CharField(blank=True, max_length=20)),
                ('source_kind_code', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '시장 품목',
                'verbose_name_plural': '시장 품목',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['source', 'source_item_code', 'source_kind_code'], name='market_mark_source_539af4_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketPriceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(help_text='가격이 유효한 날짜', verbose_name='관측일(valid_at)')),
                ('region', models.CharField(blank=True, max_length=40, verbose_name='지역')),
                ('market_type', models.CharField(choices=[('retail', '소매'), ('wholesale', '도매')], default='retail', max_length=12)),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='등급')),
                ('unit', models.CharField(default='g', max_length=10, verbose_name='표준단위')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='표준단위당 가격(KRW)')),
                ('source', models.CharField(default='kamis', max_length=20, verbose_name='출처')),
                ('raw_ref', models.CharField(blank=True, max_length=255, verbose_name='원본 참조')),
                ('collected_at', models.DateTimeField(verbose_name='수집 시각')),
                ('first_collected_at', models.DateTimeField(blank=True, null=True, verbose_name='최초 수집 시각')),
                ('quality_flag', models.CharField(choices=[('ok', '정상'), ('anomaly_jump', '급등락 의심'), ('nonpositive', '0/음수'), ('imputed', '대체값'), ('stale', '장기 동일값')], default='ok', max_length=20)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='market.ingestionrun')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='market.marketitem')),
            ],
            options={
                'verbose_name': '시장 가격 관측',
                'verbose_name_plural': '시장 가격 관측',
                'ordering': ['item', '-observation_date'],
                'indexes': [models.Index(fields=['item', 'observation_date'], name='market_mark_item_id_20f685_idx'), models.Index(fields=['observation_date'], name='market_mark_observa_90f4e1_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'item', 'observation_date', 'region', 'market_type', 'grade', 'unit'), name='uq_market_price_natural_key')],
            },
        ),
    ]
