# Generated by Django 5.2.13 on 2026-06-24 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='행정코드 또는 표준 지역코드', max_length=20, unique=True)),
                ('name', models.CharField(max_length=50, verbose_name='지역명')),
            ],
            options={
                'verbose_name': '생산 지역',
                'verbose_name_plural': '생산 지역',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropGrowthStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=30, verbose_name='생육단계')),
                ('start_day', models.PositiveSmallIntegerField(verbose_name='시작 일자(1~366)')),
                ('end_day', models.PositiveSmallIntegerField(verbose_name='종료 일자(1~366)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_stages', to='market.marketitem')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='growth_stages', to='market.productionregion')),
            ],
            options={
                'verbose_name': '생육단계',
                'verbose_name_plural': '생육단계',
                'ordering': ['item', 'start_day'],
            },
        ),
        migrations.CreateModel(
            name='CropProductionRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0, verbose_name='주산지 비중(0~1)')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='적용 시작일')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_regions', to='market.marketitem')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_shares', to='market.productionregion')),
            ],
            options={
                'verbose_name': '품목 주산지 비중',
                'verbose_name_plural': '품목 주산지 비중',
                'ordering': ['item', '-weight'],
                'unique_together': {('item', 'region', 'valid_from')},
            },
        ),
        migrations.CreateModel(
            name='WholesaleAuctionObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_date', models.DateField(verbose_name='경락일(valid_at)')),
                ('market', models.CharField(max_length=40, verbose_name='도매시장')),
                ('origin', models.CharField(blank=True, max_length=40, verbose_name='산지')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='등급')),
                ('unit', models.CharField(default='g', max_length=10, verbose_name='표준단위')),
                ('price', models.DecimalField(decimal_places=4, max_digits=14, verbose_name='표준단위당 낙찰가(KRW)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True, verbose_name='거래량(표준단위)')),
                ('source', models.CharField(default='wholesale', max_length=20)),
                ('raw_ref', models.CharField(blank=True, max_length=255)),
                ('collected_at', models.DateTimeField(verbose_name='수집 시각')),
                ('first_collected_at', models.DateTimeField(blank=True, null=True)),
                ('quality_flag', models.CharField(choices=[('ok', '정상'), ('anomaly_jump', '급등락 의심'), ('nonpositive', '0/음수'), ('imputed', '대체값'), ('stale', '장기 동일값')], default='ok', max_length=20)),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auction_observations', to='market.ingestionrun')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_observations', to='market.marketitem')),
            ],
            options={
                'verbose_name': '도매 경락 관측',
                'verbose_name_plural': '도매 경락 관측',
                'ordering': ['item', '-observation_date'],
                'indexes': [models.Index(fields=['item', 'observation_date'], name='market_whol_item_id_f9c9ee_idx'), models.Index(fields=['market', 'observation_date'], name='market_whol_market_4f2764_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'item', 'observation_date', 'market', 'origin', 'grade', 'unit'), name='uq_wholesale_natural_key')],
            },
        ),
    ]
